### ISSUE TITLE
Custom Classes incompatible with Dataview

### ISSUE THREAD

**Issue by ryankeppy** [LilaRest/obsidian-custom-classes#1]
Great plugin! However, I noticed after using it for a few days that my links in dataview tables/lists no longer function (clicking and page preview hover are both broken). I tried this in a sandbox vault with just dataview and custom-classes plugins installed -- default settings. Not sure if it's an issue on the dataview side or custom-classes, but figured I would report it here to see if you can replicate. You may have to restart Obsidian after enabling the plugins to encounter it.

**Comment by LilaRest** [comment]
@ryankeppy I've identified the problem, I'll release a patch soon.

Since you are a Dataview user, note that today I've also pushed a release that allows to add a custom class to a Dataview code block (e.g. if you want to style the render of the query) ^^

**Comment by ryankeppy** [comment]
Sounds great, will definitely check it out!
