### ISSUE TITLE
Use case example — custom inline formatting

### ISSUE THREAD

**Issue by anareaty** [LilaRest/obsidian-custom-classes#3]
Hi! I played with your plugin a little bit and come up with some ideas I find useful. One of them is custom inline formatting, not supported by default Markdown. For this to work formatted text and the custom class code must be put inside of any Markdown tags, so it is separated from the whole line. Here is some examples:

## Additional highliting colors
Css:
```
mark.hl-orange {
background-color: rgba(208,138,112, 0.2);
}

mark.hl-green {
background-color: rgba(163,190,140, 0.2);
}
```

Result:

![hl](https://user-images.githubusercontent.com/55949830/220536042-bd8dc362-e3b1-4a62-9c61-9eb1f91b5b14.jpg)

## Underline
Css:
```
.underline {
font-style: normal;
text-decoration: underline;
}
```

Result:

![under](https://user-images.githubusercontent.com/55949830/220536103-d26334ff-b46b-45c0-a15e-6f49a6b9509c.jpg)

## Superscript
Css:
```
.super {
font-style: normal;
vertical-align: super;
font-size: var(--font-smallest);
}
```

Result:

![super](https://user-images.githubusercontent.com/55949830/220536286-b9dfcea8-be26-4d51-ada9-01fc86f4e136.jpg)

## Subscript
Css:
```
.sub {
font-style: normal;
vertical-align: sub;
font-size: var(--font-smallest);
}
```

Result:

![sub](https://user-images.githubusercontent.com/55949830/220535872-f12b2af7-b598-4657-8d24-dea104e2783e.jpg)

To make it easier to work with these custom formattings I use the combination of [Wrap with shortcuts](https://github.com/manic/obsidian-wrap-with-shortcuts) plugin and [Editing Toolbar](https://github.com/cumany/obsidian-editing-toolbar) plugin. The first lets you create commands for wrapping text in any tags (including custom classes code as part of the tag), and the second allows to put these commands on the toolbar, you can even add custom icons. It works great together!

![wrap](https://user-images.githubusercontent.com/55949830/220536331-5f9578cb-54c9-4282-a54e-9c47766ac700.jpg)

![edit](https://user-images.githubusercontent.com/55949830/220536349-fb8f9d00-429c-4b30-bee2-d0f2c5f314c2.jpg)

By tha way, I wanted to say that your plugin is great and creates so many possibilities! It's just something I come up with lately, but there are definitely much more possible uses. Thank you for your work! 
(Sorry if my English is bad).

**Comment by LilaRest** [comment]
@anareaty Wow this is brilliant ! I've never thought of using _Custom Classes_ blocks for styling inline formatting.

I'll definitely add this in the "Demonstrations" section of the `README.md` file of this repo.

By the way if the plugin is used for this kind of tiny inline styling, I will add an even more shorthand version that just starts with a dot : `.my-class` is equivalent to `cls: my-class`

Thanks again for your contributions ! And glad to hear that this plugin is useful to you :smile:
