### ISSUE TITLE
False Positives on codeblock recognition

### ISSUE THREAD

**Issue by ggstrader** [LilaRest/obsidian-custom-classes#5]
**Describe the bug**
The latest release errors out on some dataview and other miscellaneous code blocks. Likely from the regex changes.

**To Reproduce**
Add the either of the following code blocks to a note:
````
```
{
	"nodes": [
		{"type":"file","file":"~scratch/~Scratch Note.md","id":"51a302447eea7b0d","x":-40,"y":-398,"width":221,"height":98},
	]
}
```
````

![image](https://user-images.githubusercontent.com/101308963/221076892-5b28adb4-9fdd-4904-bd0f-46d2c6affbb9.png)

````
```dataviewjs
dv.paragraph(
  `${backticks}${mermaidConf}
${list}
${backticks} 
`
);
```
````
![image](https://user-images.githubusercontent.com/101308963/221077369-74f985d0-de20-444f-99b6-b56862afbbbc.png)

**Device (please complete the following information):**
 - Operating System: Windows 10
 - Obsidian version:
![image](https://user-images.githubusercontent.com/101308963/221076943-9a6c2eed-a4d3-4e51-8e9b-c5812ae63a54.png)

**Comment by ggstrader** [comment]
Looks like it's this line:
https://github.com/LilaRest/obsidian-custom-classes/blob/3ff6beaa83fe55393ee774b0d97ba0fb0a3dc5b5/src/utils.ts#L3
@LilaRest is there a reason for the `\s*` at the beginning?

**Comment by LilaRest** [comment]
@ggstrader Yeah I noticed this one yesterday before sleeping. I'm busy for 2 days but will try to fix this one the next week.

The `\s*` at the beginning is here to allows custom classes blocks to be detected even if the user add trailing spaces, e.g. `  class: wow`

**Comment by ggstrader** [comment]
> @ggstrader Yeah I noticed this one yesterday before sleeping. I'm busy for 2 days but will try to fix this one the next week.
> 
> The `\s*` at the beginning is here to allows custom classes blocks to be detected even if the user add trailing spaces, e.g. `  class: wow`

I'd suggest either `[^\S\n]*` or just limiting it to at most one space (`\s?`), since it's matching across newlines

**Comment by ku-zhen** [comment]
Maybe it's some related problems：
- In the note where the code block exists, the following error occurs

![image](https://user-images.githubusercontent.com/61906420/221351133-2e42ea3c-8fd6-4866-aae7-345560b4a7eb.png)

**Comment by LilaRest** [comment]
> I'd suggest either `[^\S\n]*` or just limiting it to at most one space (`\s?`), since it's matching across newlines

@ggstrader I've implemented ` *` instead, which is more simple and will allow an unlimited number of space without matching line break, and other white-space chars. 

I'll push a new version of the plugin in the day with that change.
